### PR TITLE
ManagedExec: close only FDs that have been opened

### LINKED ISSUE #3158: High limit of open file descriptors slows down `exec` wrapper
The cvmfs utility code that wraps `exec` closes all possible open file descriptors (with some exceptions) before starting the new process.  That becomes an issue as the limit on open file descriptors gets very high, as found in [this post](https://cernvm-forum.cern.ch/t/cvmfs-config-setup-hangs/275)

### PR DESCRIPTION
**Pull request by gman0**
This PR replaces the current way of closing FDs before `exec()`. Instead iterating over 0..max_fd and doing as many `close()` syscalls, look into what FDs are actually open and `close` only those.

I have a version with [`close_range()`](https://man7.org/linux/man-pages/man2/close_range.2.html) too, but this might be sufficient for now?

With this patch:
```
[root@a9f6578addd9 cvmfs]# ulimit -n
1073741816
[root@a9f6578addd9 cvmfs]# time ./cvmfs2 -o parse,debug '' /mnt -d --foreground
Debug: using library ./libcvmfs_fuse3_stub.so
# CernVM-FS parameters:


real	0m0.005s
user	0m0.002s
sys	0m0.002s
```

Without this patch, with this `ulimit -n`, it takes around 45min.

Fixes: https://github.com/cvmfs/cvmfs/issues/3158

### CODE REVIEW

**Comment by gman0** [comment]
P.S. I didn't test this on OSX as I don't have it at hand.

**Review by jblomer — CHANGES_REQUESTED** [review]
Great! Many thanks for the patch!

The effort to scan /proc/self/fd should still be high compared to just closing some file descriptors if the fd limit is low. I'd suggest to still check for `_SC_OPEN_MAX` and switch to the new mechanism only as of a threshold (100k? 1M? You probably have some numbers at hand).

We can also stick to the current way of closing all files on macOS.

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by gman0** [comment]
I can squash once we're done with reviews.

**Comment by gman0** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Comment by jblomer** [comment]
@cernvm-bot unittest

File: cvmfs/util/posix.cc [hunk 1]
```diff
@@ -1750,6 +1750,70 @@ struct ForkFailures {  // TODO(rmeusel): C++11 (type safe enum)
...
+ * To be used after fork but before exec.
+ */
+static bool CloseAllFildes(const std::set<int> &preserve_fildes)
+{
+  int max_fd = static_cast<int>(sysconf(_SC_OPEN_MAX));
+  if (max_fd < 0) {
+    return false;
+  }
+
+  auto close_all_until_maxfd = [&preserve_fildes](int max_fd){
```
Comment (jblomer) [inline cvmfs/util/posix.cc]: Cvmfs is C++03, this won't compile on all supported platforms.

**Review by jblomer — CHANGES_REQUESTED** [review]
In principle looks good but needs to be C++03.

File: cvmfs/util/posix.cc (hunk 1 above)
Comment (gman0) [reply cvmfs/util/posix.cc]: Ah ok, I'll redo it for that.

File: cvmfs/util/posix.cc [hunk 2]
```diff
@@ -1808,15 +1883,8 @@ bool ManagedExec(const std::vector<std::string>  &command_line,
...
-    if (max_fd < 0) {
-      failed = ForkFailures::kFailGetMaxFd;
-      goto fork_failure;
-    }
-    for (int fd = 0; fd < max_fd; fd++) {
-      if ((fd != pipe_fork.write_end) && (preserve_fildes.count(fd) == 0)) {
-        close(fd);
-      }
+    if (!CloseAllFildes(skip_fds)) {
+      failed = ForkFailures::kUnknown;
```
Comment (jblomer) [inline cvmfs/util/posix.cc]: Let's rename `kFailGetMaxFd` to `kFailCloseFds`

**Review by jblomer — CHANGES_REQUESTED** [review]
Great, many thanks!  One more nit, and most likely a few linter errors.

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Comment by jblomer** [comment]
@cernvm-bot unittest

File: cvmfs/util/posix.cc (hunk 2 above)
Comment (jblomer) [inline cvmfs/util/posix.cc]:
```suggestion
      failed = ForkFailures::kFailCloseFds;
      goto fork_failure;
```

**Review by jblomer — CHANGES_REQUESTED** [review]
Thanks for renaming that enum constant! There was just the oversight of then using it instead of `kUnknown`.

File: cvmfs/util/posix.cc (hunk 2 above)
Comment (gman0) [reply cvmfs/util/posix.cc]: Yes, I wasn't very happy with `kUnknown` either. Just to clarify, do you want me to drop the rename commit and use `kFailGetMaxFd` instead?

Comment (jblomer) [reply cvmfs/util/posix.cc]: Eh, sorry, my bad.  I meant using the new kFailCloseFds of course.

Comment (jblomer) [reply cvmfs/util/posix.cc]: I updated the suggestion

Comment (gman0) [reply cvmfs/util/posix.cc]: I somehow missed renaming this bit and actually using the new error code, sorry. It should be fixed now.

**Comment by jblomer** [comment]
@cernvm-bot tidy

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by jblomer** [comment]
@cernvm-bot cpplint

**Comment by jblomer** [comment]
@cernvm-bot unittest

**Comment by gman0** [comment]
@jblomer all tests passed. Let me know if there are any more changes needed or you want me to squash the commits. Thanks!

**Review by jblomer — APPROVED** [review]

**Comment by jblomer** [comment]
Very nice, thanks a lot! I'll add a round of integration tests and if they look good, we'll merge.  This patch targets the 2.11 release in ~May. Please let us know if you need a nightly build for deployment.

**Comment by jblomer** [comment]
@cernvm-bot cloudtest
