### PR TITLE
Avoid a use after delete error

### LINKED ISSUE #3863: SIGSEGV while logging "failed to umount %s (%d)"
A build of devel branch as of 00718c6e3e24a9ee4f8d38a710b3460d7aa62ec0 (with local commits not altering the product code) on Fedora 42, running integration tests, generates a lot of core dumps. Haven't correlated to specific tests but `coredumpctl` shows a lot of them, possibly many tests trigger this in my case.

I am suspicious that recent commit 840da9cc5d6ef410f188f79c40cb90f64f534a25 introduced `goto cleanup` between `delete mount_point_;` and `mount_point_ = NULL;`, so possibly the process called `mount_point_->c_str()` and dereferenced its result.

```
 # coredumpctl debug
           PID: 1035702 (cvmfs2)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 11 (SEGV)
     Timestamp: Tue 2025-06-10 11:51:49 UTC (10h ago)
  Command Line: /usr/bin/cvmfs2 -o rw,system_mount,fsname=cvmfs2,allow_other,grab_mountpoint,uid=995,gid=995 cvmfs-config.cern.ch /cvmfs/cvmfs-config.cern.ch
    Executable: /usr/bin/cvmfs2
 Control Group: /system.slice/autofs.service
          Unit: autofs.service
         Slice: system.slice
       Boot ID: 97ff4af5c88244eab5c09be5b9600975
    Machine ID: a309363c8aad425c9edc49e5ee6bad33
      Hostname: fedora
       Storage: /var/lib/systemd/coredump/core.cvmfs2.0.97ff4af5c88244eab5c09be5b9600975.1035702.1749556309000000.zst (present)
  Size on Disk: 320.2K
       Package: cvmfs/2.13.0-1.fc42
      build-id: 204dd58539a6ca4d6497c60211ea544ee66403d4
       Message: Process 1035702 (cvmfs2) of user 0 dumped core.

                Module /usr/bin/cvmfs2 from rpm cvmfs-2.13.0-1.fc42.x86_64
                Module libz.so.1 from rpm zlib-ng-2.2.4-3.fc42.x86_64
                Module libcrypto.so.3 from rpm openssl-3.2.4-3.fc42.x86_64
                Module libssl.so.3 from rpm openssl-3.2.4-3.fc42.x86_64
                Module libfuse3.so.3 from rpm fuse3-3.16.2-5.fc42.x86_64
                Module libcvmfs_fuse3_stub.so from rpm cvmfs-2.13.0-1.fc42.x86_64
                Stack trace of thread 1035702:
                #0  0x00007fbdf54a267a __strlen_sse2 (libc.so.6 + 0x9467a)
                #1  0x00007fbdf544ede8 __printf_buffer (libc.so.6 + 0x40de8)
                #2  0x00007fbdf5473299 __vasprintf_internal (libc.so.6 + 0x65299)
                #3  0x00007fbdf590a4bd vasprintf (libcvmfs_fuse3_stub.so + 0x44bd)
                #4  0x00007fbdf590ad3b _ZN6loader8LogCvmfsENS_9LogSourceEiPKcz (libcvmfs_fuse3_stub.so + 0x4d3b)
                #5  0x00007fbdf59116e6 _Z8FuseMainiPPc (libcvmfs_fuse3_stub.so + 0xb6e6)
                #6  0x000055aa570d7181 main (/usr/bin/cvmfs2 + 0x1181)
                #7  0x00007fbdf54115f5 __libc_start_call_main (libc.so.6 + 0x35f5)
                #8  0x00007fbdf54116a8 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x36a8)
                #9  0x000055aa570d7295 _start (/usr/bin/cvmfs2 + 0x1295)
                ELF object binary architecture: AMD x86-64
...
(gdb) print $_siginfo.si_signo
$10 = 11
(gdb) print/x $_siginfo._sifields._sigfault.si_addr
$11 = 0x55afdf447d22
(gdb) bt
#0  __strlen_sse2 () at ../sysdeps/x86_64/multiarch/strlen-sse2.S:142
#1  0x00007fbdf544ede8 in __printf_buffer (buf=buf@entry=0x7ffca0395380, format=0x7fbdf5918f9e "failed to umount %s (%d)", ap=0x7ffca03965e0, mode_flags=2)
    at /usr/src/debug/glibc-2.41-5.fc42.x86_64/stdio-common/vfprintf-process-arg.c:435
#2  0x00007fbdf5473299 in __vasprintf_internal (result=0x7ffca03954d8, format=<optimized out>, args=<optimized out>, mode_flags=<optimized out>) at vasprintf.c:102
#3  0x00007fbdf590a4bd in vasprintf (__ptr=<optimized out>, __fmt=<optimized out>, __ap=<optimized out>, __ptr=<optimized out>, __fmt=<optimized out>, __ap=<optimized out>) at /usr/include/bits/stdio2.h:275
#4  loader::vLogCvmfs (mask=36, format=<optimized out>, variadic_list=variadic_list@entry=0x7ffca03965e0, source=loader::kLogCvmfs)
    at /home/sftnight/buildpackage/BUILD/cvmfs-2.13.0-build/cvmfs-2.13.0/cvmfs/util/logging.cc:438
#5  0x00007fbdf590ad3b in loader::LogCvmfs (source=loader::kLogCvmfs, mask=mask@entry=36, format=format@entry=0x7fbdf5918f9e "failed to umount %s (%d)", source=loader::kLogCvmfs)
    at /home/sftnight/buildpackage/BUILD/cvmfs-2.13.0-build/cvmfs-2.13.0/cvmfs/util/logging.cc:548
#6  0x00007fbdf59116e6 in FuseMain (argc=<optimized out>, argv=<optimized out>) at /usr/include/c++/15/bits/basic_string.h:238
#7  0x000055aa570d7181 in main (argc=5, argv=0x7ffca0396d98) at /home/sftnight/buildpackage/BUILD/cvmfs-2.13.0-build/cvmfs-2.13.0/cvmfs/fuse_main.cc:145
```

### LINKED ISSUE #3865: cvmfs-2.13.0: segfaults and coredumps  in journalctl logs.
I am attaching output of cvmfs_config bugreport and core dumps from /var/lib/apport/coredump

[cvmfs-bugreport.tar.gz](https://github.com/user-attachments/files/20711247/cvmfs-bugreport.tar.gz)
[coredumps.tar.gz](https://github.com/user-attachments/files/20711246/coredumps.tar.gz)

### PR DESCRIPTION
**Pull request by DrDaveD**
- Fixes #3863
- Fixes #3865

### CODE REVIEW

File: cvmfs/loader.cc [hunk 1]
```diff
@@ -1233,8 +1233,6 @@ int FuseMain(int argc, char *argv[]) {
   delete fence_reload_;
   delete loader_exports_;
   delete config_files_;
-  delete repository_name_;
-  delete mount_point_;
```
Comment (jblomer) [inline cvmfs/loader.cc:1240]: I think they should still be deleted but further down, after their last use.

Comment (DrDaveD) [reply cvmfs/loader.cc:1240]: You're right.  I was thinking that setting the pointer to NULL would automatically delete it but that's not the case.

**Review by christge-sft — COMMENTED** [review]
From my point of view, deleting `repository_name_` and `mount_point_` just before setting them to `NULL` should solve the issue.

Although, I'ld like to share some thoughts that might/probably exceed the frame of the issue:
- I'ld go for a smaller `FuseMain` (more readable, understandable, maintanable)
- I'ld avoid `goto` statements
- I'ld move to a more "standard" cleanup strategy (using functions / classes-distructors). Actually, from my point of view, the `cleanup` part doesn't actually do much of a cleanup at the moment. It's mostly logging.

Do we leave all this for later? From a functional point of view, I think that with the incorporated changes, it works!

**Comment by vvolkl** [comment]
> the cleanup part doesn't actually do much of a cleanup at the moment. It's mostly logging

It does unmount on failure. But those are good points! Let's follow them up in a future PR for 2.14.

**Review by vvolkl — APPROVED** [review]

**Comment by vvolkl** [comment]
> > the cleanup part doesn't actually do much of a cleanup at the moment. It's mostly logging
> 
> It does unmount on failure. But those are good points! Let's follow them up in a future PR for 2.14.

Deprecating libfuse 2 ( at least for new installations ) might also help remove some of the complexity of this code. I'll make a dedicated issue.
