### PR TITLE
Don't terminate the watchdog on unexpected signals

### LINKED ISSUE #3808: stopping `autofs` sometimes doesn't umount /cvmfs/REPOSITORY, Ubuntu 24.04
We have seen this happing on some Ubuntu 24.04 VMs on an OpenStack platform. After a VM is launched, the [CernVM-FS client is installed, access to EESSI is configured and becomes available](https://www.eessi.io/docs/getting_access/native_installation/#__tabbed_1_2), and can be used via
```bash
source /cvmfs/software.eessi.io/versions/2023.06/init/bash
```
Then, some time later, accessing `/cvmfs/software.eessi.io` results in the error `Transport endpoint is not connected`. When inspecting `/var/log/syslog` we have seen messages such as (timestamps and machine name removed for brevity)
```log
systemd[1]: Stopping autofs.service - Automounts filesystems on demand...
cvmfs2: (software.eessi.io) watchdog: received unexpected signal 15 from PID 1 / UID 0
cvmfs2: (cvmfs-config.cern.ch) watchdog: received unexpected signal 15 from PID 1 / UID 0
cvmfs2: watchdog: received unexpected signal 15 from PID 1 / UID 0
cvmfs2: (cvmfs-config.cern.ch) watchdog disappeared, disabling stack trace reporting (revents: 16 / 8|16|32)
cvmfs2: (software.eessi.io) watchdog disappeared, disabling stack trace reporting (revents: 16 / 8|16|32)
automount[15615]: umount_autofs_indirect: ask umount returned busy /cvmfs
systemd[1]: autofs.service: Deactivated successfully.
systemd[1]: Stopped autofs.service - Automounts filesystems on demand.
```
note the line
```log
automount[15615]: umount_autofs_indirect: ask umount returned busy /cvmfs
```
and `mount | grep cvmfs` showed that the repositories were still mounted
```log
/etc/auto.cvmfs on /cvmfs type autofs (rw,relatime,fd=7,pgrp=16913,timeout=300,minproto=5,maxproto=5,indirect,pipe_ino=82658)
cvmfs2 on /cvmfs/cvmfs-config.cern.ch type fuse (ro,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
cvmfs2 on /cvmfs/software.eessi.io type fuse (ro,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other)
```
Simply restarting `autofs` via `sudo systemctl start autofs` does not resolve the issue. The error persists.

However, the issue can be resolved in different ways:
1. Running `sudo cvmfs_config killall` (and restarting `autofs` when not done yet), _or_
2. Manually removing the mountpoints, i.e., `sudo umount /cvmfs/software.eessi.io` and `sudo umount /cvmfs/cvmfs-config.cern.ch` (and restarting `autofs` when not done yet), _or_
3. Rebooting the machine

A successful stop of `autofs` would result in the following message when accessing the directory
```bash
ls: cannot access '/cvmfs/software.eessi.io': No such file or directory
```
and `syslog` contains the following lines
```log
systemd[1]: Stopping autofs.service - Automounts filesystems on demand...
cvmfs2: watchdog: received unexpected signal 15 from PID 1 / UID 0
cvmfs2: (software.eessi.io) watchdog: received unexpected signal 15 from PID 1 / UID 0
cvmfs2: (software.eessi.io) watchdog disappeared, disabling stack trace reporting (revents: 16 / 8|16|32)
cvmfs2: (cvmfs-config.cern.ch) watchdog: received unexpected signal 15 from PID 1 / UID 0
cvmfs2: (cvmfs-config.cern.ch) watchdog disappeared, disabling stack trace reporting (revents: 16 / 8|16|32)
systemd[1]: cvmfs-cvmfs\x2dconfig.cern.ch.mount: Deactivated successfully.
systemd[1]: cvmfs-software.eessi.io.mount: Deactivated successfully.
systemd[1]: autofs.service: Deactivated successfully.
systemd[1]: Stopped autofs.service - Automounts filesystems on demand.
```

### PR DESCRIPTION
**Pull request by DrDaveD**
- Fixes #3808

### CODE REVIEW

**Comment by DrDaveD** [comment]
@vvolkl must I do something about the linter error?

**Comment by DrDaveD** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
> @vvolkl must I do something about the linter error?

No, the code was never free of linter warnings and you can trigger one by changing unrelated code. We'll fix them in bulk at one point.

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

File: cvmfs/monitor.cc [hunk 1]
```diff
@@ -286,13 +286,12 @@ string Watchdog::ReportStacktrace() {
...
 
 
-void Watchdog::ReportSignalAndTerminate(
+void Watchdog::ReportSignalAndContinue(
   int sig, siginfo_t *siginfo, void * /* context */)
 {
   LogCvmfs(kLogMonitor, kLogSyslogErr,
            "watchdog: received unexpected signal %d from PID %d / UID %d",
            sig, siginfo->si_pid, siginfo->si_uid);
-  _exit(1);
```
Comment (vvolkl) [inline cvmfs/monitor.cc:295]: Should we really continue here for all signals or only for 15?

Comment (DrDaveD) [reply cvmfs/monitor.cc:295]: I think it should be for all.  The name of the variable listing all the signals is `g_suppressed_signals` so I think the intention from the beginning was to suppress them all, not to exit.  We don't want the watchdog to exit until the primary process has exited.  The watchdog can still be killed with `-9`/`SIGKILL`.

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest

**Comment by vvolkl** [comment]
@cernvm-bot cloudtest
